# Generated by Django 3.2.7 on 2021-09-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
