# Generated by Django 3.2.7 on 2021-09-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_content_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
