# Generated by Django 3.2.7 on 2021-09-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
