# Generated by Django 3.2.7 on 2021-09-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
