# Generated by Django 3.2.7 on 2021-09-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
