# Generated by Django 3.2.7 on 2021-09-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commented_by',
        ),
    ]
